/*
 *  Licensed Materials - Property of IBM
 *  5725-I43 (C) Copyright IBM Corp. 2011, 2013. All Rights Reserved.
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

//The code below WILL NOT WORK unless you call it inside or after wlCommonInit()
//This file has been generated by the JSONStore Wizard.

jsonInit = function () {

	WL.JSONStore.init({
		peopleList : {
			searchFields: {"name":"string","age":"number"}
		}
	}, {
		 password : 'PleaseChangeThisPassword'
	})

	.then(function () {
		alert("JSONStore initialization successful.");
		})

	.fail(function (errObj) {
		WL.Logger.ctx({pretty: true}).error(errObj);
	});

};